version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - myapp_network
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: rails server -b 0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - myapp_network
  redis:
    image: redis:latest
    container_name: ror-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - myapp_network
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - ./storage:/data
    command: server --console-address ":9001" /data
    networks:
      myapp_network:
        aliases:
          - my-minio-localhost-alias
networks:
  myapp_network:
    driver: bridge
volumes:
  redis_data:
    driver: local
  minio_data:
    driver: local
