development:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://redis:6379/0" } %>
  channel_prefix: testapp_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://redis:6379/0" } %>
  channel_prefix: testapp_production
