default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  host: db
  username: root
  password: root

test:
  <<: *default
  database: myapp_test
  host: db
  username: root
  password: root

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
