# config/sidekiq.yml

:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 10

:queues:
  - default
  - mailers
  - video_thumbnail_generation
  - digital_asset_demo_generate

:scheduler:
  :schedule:
    remove_unused_assets:
      cron: "* * * * *" # Every minute
      class: RemoveUnusedAssetsJob
      queue: default
      description: "Remove unused assets from storage"
